# Generated by Django 4.1.2 on 2022-10-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=255)),
                ('ultimo_nome', models.CharField(max_length=255)),
            ],
        ),
    ]
